steps:
  # 1. Terraform infrastructure
  - id: 'terraform-init'
    name: 'hashicorp/terraform:1.5.7'
    args: ['init']
    dir: 'terraform'

  - id: 'terraform-apply'
    name: 'hashicorp/terraform:1.5.7'
    args: ['apply', '-auto-approve']
    dir: 'terraform'
    waitFor: ['terraform-init']

  # 2. Build and push publisher image
  - id: 'build-publisher'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/bct-project-465419/cloud-run-source-deploy/pubsub-publisher',
      './publisher'
    ]
    waitFor: ['terraform-apply']

  - id: 'push-publisher'
    name: 'gcr.io/cloud-builders/docker'
    args: [
      'push',
      'us-central1-docker.pkg.dev/bct-project-465419/cloud-run-source-deploy/pubsub-publisher'
    ]
    waitFor: ['build-publisher']

  # 3. Deploy Cloud Run service
  - id: 'deploy-publisher'
    name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: 
      - 'gcloud'
      - 'run'
      - 'deploy'
      - 'pubsub-publisher'
      - '--image=us-central1-docker.pkg.dev/bct-project-465419/cloud-run-source-deploy/pubsub-publisher'
      - '--platform=managed'
      - '--region=us-central1'
      - '--service-account=dataflow-ca@bct-project-465419.iam.gserviceaccount.com'
      - '--no-allow-unauthenticated'
      - '--memory=256Mi'
      - '--cpu=1'
    waitFor: ['push-publisher']

  # 4. Deploy Dataflow pipeline (after image is available)
  - id: 'deploy-dataflow'
    name: 'python:3.10'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        pip install apache-beam[gcp]==2.54.0 && \
        python dataflow/pipeline.py \
          --project=bct-project-465419 \
          --region=us-central1 \
          --input_topic=projects/bct-project-465419/topics/stream-topic \
          --temp_location=gs://bct-project-465419-raw-backup/temp \
          --staging_location=gs://bct-project-465419-raw-backup/staging \
          --output_table=bct-project-465419:streaming_dataset.user_events \
          --output_path=gs://bct-project-465419-raw-backup/raw/events \
          --runner=DataflowRunner \
          --streaming
    waitFor: ['push-publisher']

options:
  logging: CLOUD_LOGGING_ONLY
timeout: 1800s